"use strict";

// The model manifest is generated by tools/export_suv_glb.py. It carries the
// versioned GLB URL, so a re-export changes this worker's imports, which makes
// the browser install a fresh worker with a fresh cache on the next reload.
const FALLBACK_MODELS = { version: "unversioned", suv: "assets/models/suv.glb" };
try {
  importScripts("./assets/models/model-manifest.js");
} catch {
  // Manifest missing: still install so the app shell works offline.
}
const MODELS = self.PARKING_HELPER_MODELS || FALLBACK_MODELS;

const CACHE_NAME = `parking-helper-shell-v2-${MODELS.version}`;
const PRECACHE_URLS = [
  "./",
  "./index.html",
  "./styles.css",
  "./app.js",
  "./assets/vendor/model-viewer.min.js",
  "./assets/models/model-manifest.js",
  `./${MODELS.suv}`,
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)),
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET" || new URL(request.url).origin !== self.location.origin) return;

  event.respondWith(
    caches
      .match(request, { ignoreSearch: request.mode === "navigate" })
      .then((cached) => {
        if (cached) return cached;
        return fetch(request).then((response) => {
          if (!response || response.status !== 200 || response.type !== "basic") return response;
          const copy = response.clone();
          event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.put(request, copy)));
          return response;
        });
      })
      .catch(() => {
        if (request.mode === "navigate") return caches.match("./index.html");
        return Response.error();
      }),
  );
});
