r"""Export the Parking Helper SUV from Blender to a web-ready GLB.

Easiest: double-click ``tools\export_suv.bat``.

Or run from the repository root with Windows cmd.exe:

    "C:\Program Files\Blender Foundation\Blender 5.2\blender.exe" -b ^
      --python tools\export_suv_glb.py

Optional paths may be supplied after ``--``:

    -- --input assets\SUV.blend --output assets\models\suv.glb

The script opens the source file, selects mesh-bearing car objects only, and
exports without saving or otherwise modifying the .blend file.

After a successful export it (re)writes ``assets\models\model-manifest.js``,
which tells app.js and the service worker which versioned URL to load
(``assets/models/suv.glb?v=<hash>``). The version is the first 10 hex digits
of the GLB's SHA-256, so it changes exactly when the model's bytes change and
stays put when they do not.

``--manifest-only`` rewrites the manifest from the GLB already on disk without
launching an export (useful outside Blender: ``python tools\export_suv_glb.py
-- --manifest-only``).
"""

import argparse
import hashlib
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = REPO_ROOT / "assets" / "SUV.blend"
DEFAULT_OUTPUT = REPO_ROOT / "assets" / "models" / "suv.glb"
DEFAULT_MANIFEST = REPO_ROOT / "assets" / "models" / "model-manifest.js"
VERSION_DIGITS = 10


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", default=str(DEFAULT_INPUT), help="Source .blend path")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Destination .glb path")
    parser.add_argument(
        "--manifest",
        default=str(DEFAULT_MANIFEST),
        help="Generated JS manifest with the versioned GLB URL",
    )
    parser.add_argument(
        "--manifest-only",
        action="store_true",
        help="Skip Blender; just rewrite the manifest from the existing GLB",
    )
    argv = []
    if "--" in sys.argv:
        argv = sys.argv[sys.argv.index("--") + 1 :]
    return parser.parse_args(argv)


def resolve_path(value):
    path = Path(value)
    return path.resolve() if path.is_absolute() else (REPO_ROOT / path).resolve()


def glb_version(glb_path):
    digest = hashlib.sha256(glb_path.read_bytes()).hexdigest()
    return digest[:VERSION_DIGITS]


def write_manifest(glb_path, manifest_path):
    """Write the cache-busting manifest consumed by index.html and the service worker."""
    if not glb_path.is_file():
        raise RuntimeError(f"Cannot write manifest; GLB is missing: {glb_path}")

    version = glb_version(glb_path)
    try:
        web_path = glb_path.relative_to(REPO_ROOT).as_posix()
    except ValueError as error:
        raise RuntimeError(
            f"GLB must live inside the repository so the app can load it: {glb_path}"
        ) from error

    contents = (
        "// GENERATED by tools/export_suv_glb.py - do not edit by hand.\n"
        "// Re-run tools/export_suv.bat after changing assets/SUV.blend.\n"
        "// `version` is the first 10 hex digits of the GLB's SHA-256; it drives\n"
        "// the service-worker cache name and the ?v= query on the GLB URL.\n"
        "self.PARKING_HELPER_MODELS = {\n"
        f'  version: "{version}",\n'
        f'  suv: "{web_path}?v={version}",\n'
        "};\n"
    )

    previous = manifest_path.read_text(encoding="utf-8") if manifest_path.is_file() else None
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(contents, encoding="utf-8", newline="\n")

    changed = previous != contents
    print(f"Manifest: {manifest_path}")
    print(f"GLB version: {version} ({'changed' if changed else 'unchanged'})")
    return version


def collect_car_objects(scene):
    mesh_objects = [obj for obj in scene.objects if obj.type == "MESH"]
    if not mesh_objects:
        raise RuntimeError("No mesh objects were found to export")

    car_objects = set(mesh_objects)
    for mesh in mesh_objects:
        parent = mesh.parent
        while parent is not None:
            if parent.type in {"CAMERA", "LIGHT"}:
                break
            car_objects.add(parent)
            parent = parent.parent

        for modifier in mesh.modifiers:
            if modifier.type == "ARMATURE" and modifier.object is not None:
                car_objects.add(modifier.object)

    return mesh_objects, sorted(car_objects, key=lambda obj: obj.name.casefold())


def validate_export_options(bpy, options):
    supported = {
        prop.identifier for prop in bpy.ops.export_scene.gltf.get_rna_type().properties
    }
    unsupported = sorted(set(options) - supported)
    if unsupported:
        raise RuntimeError(
            "This Blender glTF exporter does not support required option(s): "
            + ", ".join(unsupported)
        )


def export_glb(input_path, output_path):
    import bpy  # Only available when run inside Blender.

    if not input_path.is_file() or input_path.suffix.lower() != ".blend":
        raise RuntimeError(f"Source .blend file was not found: {input_path}")
    if output_path.suffix.lower() != ".glb":
        raise RuntimeError(f"Output must use the .glb extension: {output_path}")

    bpy.ops.wm.open_mainfile(filepath=str(input_path))
    scene = bpy.context.scene
    mesh_objects, car_objects = collect_car_objects(scene)

    bpy.ops.object.select_all(action="DESELECT")
    for obj in car_objects:
        obj.select_set(True)
    bpy.context.view_layer.objects.active = mesh_objects[0]

    selected_non_car = [
        obj.name
        for obj in bpy.context.selected_objects
        if obj.type in {"CAMERA", "LIGHT"}
    ]
    if selected_non_car:
        raise RuntimeError(
            "Refusing to export selected camera/light object(s): "
            + ", ".join(selected_non_car)
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    export_options = {
        "filepath": str(output_path),
        "check_existing": False,
        "export_format": "GLB",
        "use_selection": True,
        "export_apply": True,
        "export_normals": True,
        "export_yup": True,
        "export_cameras": False,
        "export_lights": False,
        "export_materials": "EXPORT",
        "export_animations": False,
    }
    validate_export_options(bpy, export_options)

    print(f"Blender version: {bpy.app.version_string}")
    print(f"Source: {input_path}")
    print(f"Selected car objects: {[obj.name for obj in car_objects]}")
    print("Camera/light export: disabled")
    print("Modifiers: applied in exported geometry")
    print("Normals: included")
    print("Axis convention: +Y up")

    result = bpy.ops.export_scene.gltf(**export_options)
    if "FINISHED" not in result:
        raise RuntimeError(f"glTF export failed with result: {sorted(result)}")
    if not output_path.is_file():
        raise RuntimeError(f"Exporter reported success but output is missing: {output_path}")

    print(f"Output: {output_path}")
    print(f"Output bytes: {output_path.stat().st_size}")


def main():
    args = parse_args()
    input_path = resolve_path(args.input)
    output_path = resolve_path(args.output)
    manifest_path = resolve_path(args.manifest)

    if not args.manifest_only:
        export_glb(input_path, output_path)
    write_manifest(output_path, manifest_path)


if __name__ == "__main__":
    main()
